/**
 * Dental-clinic-Dallas - Frontend App
 * Auto-generated by Module Library Assembler
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';

// Module imports
// No modules imported

// Home page component
function HomePage() {
  return (
    <div style={{ 
      padding: '40px', 
      maxWidth: '800px', 
      margin: '0 auto',
      fontFamily: '-apple-system, sans-serif'
    }}>
      <h1 style={{ 
        fontSize: '48px',
        background: 'linear-gradient(135deg, #f97316, #8b5cf6)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginBottom: '10px'
      }}>
        Dental-clinic-Dallas
      </h1>
      <p style={{ color: '#888', marginBottom: '30px' }}>
        Your app is running! Edit src/App.jsx to customize.
      </p>
      
      <div style={{ 
        background: 'rgba(255,255,255,0.05)', 
        borderRadius: '12px', 
        padding: '24px',
        border: '1px solid rgba(255,255,255,0.1)'
      }}>
        <h3 style={{ marginBottom: '16px', color: '#22c55e' }}>Available Routes:</h3>
        <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
          <li style={{ padding: '8px 0' }}>
            <Link to="/" style={{ color: '#f97316' }}>/ - Home</Link>
          </li>

        </ul>
      </div>
      
      <div style={{ marginTop: '30px', color: '#666', fontSize: '14px' }}>
        <p>Backend API: <a href="http://localhost:5000/health" style={{ color: '#f97316' }}>http://localhost:5000/health</a></p>
      </div>
    </div>
  );
}

function App() {
  return (
    <BrowserRouter>
      
        <div className="app" style={{ minHeight: '100vh', background: '#0a0a0f', color: '#e4e4e4' }}>
          
          
          <main>
            <Routes>
              <Route path="/" element={<HomePage />} />

            </Routes>
          </main>
          
          
        </div>
      
    </BrowserRouter>
  );
}

export default App;
